### ISSUE TITLE
No resource identifier found for attribute

### ISSUE THREAD

**Issue by CharafHormi** [grendio/XBottomSheet#1]
Hello,

It looks like nuget doesn't actually install attr.xml which give me "No resource identifier found for attribute " compile error for 
```
app:anchorOffset="320dp"
app:peekHeight="192dp"
app:defaultState="collapsed"
```
Adding it manually in my project resolves that error but then it gives me a weird behavior of the control taking half the screen while collapsed  and not just the peekheight

**Comment by AlexStefan** [comment]
Hello,

There is a strange behaviour with the attr.xml because of the Nuget behaviour. Make sure that is added as a nuget, not as a nuget reference. (read more on https://stackoverflow.com/questions/50909751/copy-files-to-android-project-on-nuget-installation)
For the weird behaviour, @butonium  will come with details. 

Thank you,
Alexandru

**Comment by butonium** [comment]
Can you try to assign the values programmatically? I will investigate the parsing issue later today.

**Comment by butonium** [comment]
I couldn't reproduce the issue with your values. Can you give us some details about what device are you using? (perhaps we missed something)

**Comment by CharafHormi** [comment]
Ok so I just created a new Xamarin.Android project, installed the nuget , and added `<XBottomSheet.Droid.Views.XBottomSheetView
	android:id="@+id/BottomSheet"
	app:anchorOffset="320dp"
	app:peekHeight="192dp"
	app:defaultState="collapsed"
	android:layout_width="match_parent"
	android:layout_height="match_parent">
   </XBottomSheet.Droid.Views.XBottomSheetView>`

I get 
![1](https://user-images.githubusercontent.com/5833461/51894021-eda3f780-23a6-11e9-928c-db0fa36c1a03.PNG)

I then removed those from the axml, assigned PeekHeight programmaticaly (the other 2 are not accessible?) and deployed to emulator (Note that this is collapsed state)
![2](https://user-images.githubusercontent.com/5833461/51894375-dfa2a680-23a7-11e9-877a-dbfcd2c0e160.PNG)


The emulator is on API27 if that helps, Same as target Android version

**Comment by AlexStefan** [comment]
Ok, just to check if we understand it right: You have peakheight set at quite some height, but you'd expect it to be much lower, right? The collapsed state is represented by peakheight. 
What is you expected behaviour? Can you put the new Xamarin.Android project in a public repo and give use the link? After providing the link we'll look over and come with details or fixes for the mentioned problems.
For the 'defaultState' and 'anchorOffset' you're right, they are not public, we will put that in the next release, which will happen after we fix the issues that you're mentioning.

**Comment by AlexStefan** [comment]
We've managed to repro your scenario and together with other changes we've published a new beta version on the [NuGet](https://www.nuget.org/packages/XBottomSheet/1.0.2-beta). Please check it out and tell us if you still encounter issues. Also do note that in order to prevent any strange behaviour the control needs AppCompat theme within your app.

**Comment by CharafHormi** [comment]
After updating to the beta version it is resolved. Works both from xml attributes and programmaticaly.

Thanks,

**Comment by butonium** [comment]
Thank you for your report.
